trigger: none

pool: powermanage-pool

stages:
- stage: Build
  displayName: Build & Code Quality
  jobs:
  - job: BuildPythonApp
    displayName:  Build Python Application
    steps:  
    
    - task: PowerShell@2
      displayName: Check Python Version & Install Lint Tool
      inputs:
        targetType: 'inline'
        script: |
          python --version
          pip install ruff

    # - task: PowerShell@2
    #   displayName: Run Python Linting (Ruff)
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       python -m ruff --version
    #       python -m ruff check app.py

    - task: PublishPipelineArtifact@1
      displayName: Publish Application Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/app.py'
        artifact: 'todoapi_artifact'
        publishLocation: 'pipeline'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'todoapi_artifact'
        targetPath: '$(Pipeline.Workspace)/todoapi_artifact'


    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/todoapi_artifact'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
        replaceExistingArchive: true
